site_name: Mayank Parasar
site_author: Mayank Parasar


# Repository
repo_name: Mayank-Parasar/website
repo_url: https://github.com/Mayank-Parasar/website.git
edit_uri: ""

nav:
  - Home: index.md
  - Biography: bio.md
  - Education: education.md

theme:
  name: material
