site_name: Mayank Parasar
site_author: Mayank Parasar


# Repository
repo_name: Mayank-Parasar/website
repo_url: https://github.com/Mayank-Parasar/website.git
edit_uri: ""

nav:
  - Home: index.md
  - Service: service.md
  # - Biography: bio.md
  - Education: education.md
  - Research: research.md
  - Publications: publication.md
  - Experience: experience.md
  - Skills: skill.md
  # - Project Code Hosting: codes.md
  - Social: extracurricular.md
  - GitHub Projects: github.md
  - Curriculum Vitae: cv.md
  - Blog: blog.md
  # - Gallery: gallery.md

theme:
  name: material


# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Mayank-Parasar/leetcode
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mayankparasar/