site_name: Mayank Parasar
site_author: Mayank Parasar


# Repository
repo_name: Mayank-Parasar/website
repo_url: https://github.com/Mayank-Parasar/website.git
edit_uri: ""

nav:
  - Home: index.md
  # - Biography: bio.md
  - Education: education.md
  - Research: research.md
  - Publications: publication.md
  - Experience: experience.md
  - Skills: skill.md
  - Project Code Hosting: codes.md
  - Extracurricular: extracurricular.md
  - Curriculum Vitae: cv.md
  # - Gallery: gallery.md

theme:
  name: material
